### ISSUE TITLE
Add new projects throws errors

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#274] opened 2024-04-23 07:44 UTC
**Cannot add new projects**
An error is been thrown in the console when tried to add new project after the fresh installation.

**Steps To Reproduce**
1. Install latest version of PASTA
2. Open Pasta App, Go to projects view and click on add button
3. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/6c016e4c-e56b-461d-825d-674e00ad5bf7)
4. Enter the project information and click on 'Save' or 'Save & Next' button
5. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/eb157da6-dbb7-42db-b595-ece19e722af7)
6. Nothing happens on button click but for the error thrown on the app console as shown below
7. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/42c05fe6-7632-4d4d-ab7f-c0d3d068817e)

**Expected behavior**
Both 'Save' and 'Save & Next' button click should create the projects and the UI should be updated appropriately with no errors been thrown.

**Desktop (please complete the following information):**
 - OS: 22.04.1-Ubuntu
 - Browser: Chrome
 - PASTA ELN Version:

**Comment by jmurugan-fzj** [comment] 2024-04-23 07:46
@SteffenBrinckmann Please see this, might be a regression caused by the changes done as part of #266

**Comment by HTsybenko** [comment] 2024-05-17 09:04
I could not reproduce this issue in pasta_eln-2.5.3b1. It would be nice if @jmurugan-fzj could also verify that it is fixed now.

**Comment by jmurugan-fzj** [comment] 2024-06-17 14:06
@HTsybenko @SteffenBrinckmann Yes this was an issue in one of the intermediate commits, I cannot reproduce it anymore too..

**Comment by SteffenBrinckmann** [comment] 2024-06-17 15:39
If it cannot be reproduced, close it please

**Closed** 2024-06-18 08:52 UTC
Labels: bug, PR created
