### ISSUE TITLE
Deleting a data type

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#207] opened 2024-03-04 15:33 UTC
Non-structural data types  (Measurements, samples, etc.) can be deleted. 
This does not remove the items of this type from the project, however, the tables of the deleted data types cannot be accessed anymore, which might make it more difficult to curate.

 What would be the correct way if a data type is deleted - move the files of such category to unidentified?

**Comment by HTsybenko** [comment] 2024-03-15 10:44
After the removal of the data type, the items of that type are moved to "unidentified" table.

The unidentified table also has the following look and includes the PASTA-related metadata (likely not intended):
![Screenshot from 2024-03-15 11-39-12](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/3c238352-1405-4e73-a7bb-060a006d02d2)

**Comment by SteffenBrinckmann** [comment] 2024-03-15 14:14
@HTsybenko Your call since this is not a crashing bug and I currently work on the corrosion stuff and cannot test/verify/debug it:
- do you want to pause the release of 2.5.0 until this is fixed
- do you want to move it to 2.6 or so

**Comment by SteffenBrinckmann** [comment] 2024-03-16 06:08
OK, I tried it myself, and it works as intended. For you not, clearly.
The colums of the unidentified, is addressed in #170  and I added a comment there, that we check if the colums remain correct after deleting an document-type.

**Closed by SteffenBrinckmann** 2024-03-16 06:08 UTC
