### ISSUE TITLE
Changing data types and rerunning extractors

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#136] opened 2023-11-10 17:41 UTC
- Go to procedures, selection-toggle selection, then selection and group edit and change type to measurements. 
- Open measurements table, select all (toggle selection), go to selection- rerun extractors.

Verification results after this step :

measurement without shasum: m-03f9ab494528463082d2ebcdd94a520d simple.csv
measurement without shasum: m-0f78cb72b1054caba9ae4d0ff43600ce https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Misc_pollen.jpg/315px-Misc_pollen.jpg
measurement without shasum: m-a4cfc9eea4d6457f80d9740fccbc2e13 simple.png
measurement without shasum: m-edefca99c94c4973ad66d7e85d85cc2b Example_SOP.md

- After that, in the measurements table view, go to selection- toggle selection, and then execute  group edit- change type to procedures.

All items that were selected will disappear from the measurements table and do not appear in the procedures.

Verification results:
File on harddisk but not DB: PastasExampleProject/002_DataFiles/simple.png
File on harddisk but not DB: PastasExampleProject/002_DataFiles/simple.csv

Full log:
11-10 18:28:53|INFO:Start PASTA GUI
11-10 18:28:53|INFO:End PASTA GUI
11-10 18:29:05|DEBUG:table:changeTable |procedure|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:29:06|DEBUG:details:changeDetails |p-aed91c370ac04debbab35d01c23178a2|
11-10 18:29:07|DEBUG:details:changeDetails |p-aed91c370ac04debbab35d01c23178a2|
11-10 18:29:08|DEBUG:gui:formdoc ['p-aed91c370ac04debbab35d01c23178a2']
11-10 18:29:11|INFO: traceback remove:p-aed91c370ac04debbab35d01c23178a2 startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.remove(doc['_id'])
11-10 18:29:11|DEBUG:successfully saved doc with type and branch m-edefca99c94c4973ad66d7e85d85cc2b measurement  |  [{'stack': ['x-21204d05efc14993bc9e7c9b7e8d250c'], 'child': 9999, 'path': 'StandardOperatingProcedures/Example_SOP.md', 'show': [True, True]}]

11-10 18:29:11|DEBUG:details:changeDetails |redraw|
11-10 18:29:11|DEBUG:table:changeTable |||
11-10 18:29:11|DEBUG:table:changeTable |procedure||
11-10 18:29:12|DEBUG:table:changeTable |sample|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:29:12|DEBUG:table:changeTable |measurement|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:29:14|DEBUG:details:changeDetails |m-edefca99c94c4973ad66d7e85d85cc2b|
11-10 18:29:24|DEBUG:database.update.3: doc update success: m-03f9ab494528463082d2ebcdd94a520d simple.csv

11-10 18:29:24|DEBUG:database.update.3: doc update success: m-0f78cb72b1054caba9ae4d0ff43600ce https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Misc_pollen.jpg/315px-Misc_pollen.jpg

11-10 18:29:24|DEBUG:database.update.3: doc update success: m-a4cfc9eea4d6457f80d9740fccbc2e13 simple.png

11-10 18:29:24|INFO:user has strange wish: trust him/her: measurement  procedure/markdown
11-10 18:29:24|DEBUG:database.update.3: doc update success: m-edefca99c94c4973ad66d7e85d85cc2b Example_SOP.md

11-10 18:29:24|DEBUG:table:changeTable |||
11-10 18:29:24|DEBUG:details:changeDetails |redraw|
11-10 18:29:25|DEBUG:details:changeDetails |m-edefca99c94c4973ad66d7e85d85cc2b|
11-10 18:29:26|DEBUG:details:changeDetails |m-a4cfc9eea4d6457f80d9740fccbc2e13|
11-10 18:30:54|DEBUG:table:changeTable |instrument|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:30:55|DEBUG:table:changeTable |sample|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:30:56|DEBUG:table:changeTable |measurement|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:31:00|DEBUG:gui:formdoc ['m-03f9ab494528463082d2ebcdd94a520d', 'm-0f78cb72b1054caba9ae4d0ff43600ce', 'm-a4cfc9eea4d6457f80d9740fccbc2e13', 'm-edefca99c94c4973ad66d7e85d85cc2b']
11-10 18:31:05|INFO: traceback remove:m-03f9ab494528463082d2ebcdd94a520d startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.remove(doc['_id'])
11-10 18:31:05|ERROR:could not save, likely JSON issue; Check logging file
11-10 18:31:05|ERROR:could not save, likely JSON issue
11-10 18:31:05|ERROR:{'-name': 'simple.csv', '-user': 'htsybenko', '-type': ['procedure'], 'metaVendor': {'fileExtension': 'csv'}, 'metaUser': {'max': 0.9996, 'min': -0.9962}, '-branch': [{'stack': ['x-21204d05efc14993bc9e7c9b7e8d250c', 'x-73b9415234e742a29fbe5be85c5d88b6'], 'child': 9999, 'path': 'PastasExampleProject/002_DataFiles/simple.csv', 'show': [True, True, True]}], '-date': '2023-11-10T18:31:05.210150', 'comment': '', '-tags': [], '-client': 'startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.saveDoc(doc)', '_attachments': {'v0.json': {'content_type': 'application/json', 'revpos': 3, 'digest': 'md5-Za5F6kmFu/GGxl6sdD5Hgg==', 'length': 397, 'stub': True}}, '_id': 'p-4525100509a945e08ba6e6e80246dc96'}
11-10 18:31:05|ERROR:Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 242, in saveDoc
    res = self.db.create_document(doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/database.py", line 191, in create_document
    doc.create()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/document.py", line 161, in create
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed missing_stub Invalid attachment stub in p-4525100509a945e08ba6e6e80246dc96 for v0.json for url: http://127.0.0.1:5984/research

11-10 18:31:05|INFO: traceback remove:m-0f78cb72b1054caba9ae4d0ff43600ce startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.remove(doc['_id'])
11-10 18:31:05|ERROR:could not save, likely JSON issue; Check logging file
11-10 18:31:05|ERROR:could not save, likely JSON issue
11-10 18:31:05|ERROR:{'-name': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Misc_pollen.jpg/315px-Misc_pollen.jpg', 'comment': '', '-user': 'htsybenko', '-type': ['procedure'], 'metaVendor': {'fileExtension': 'jpg'}, 'metaUser': {'number pixel': 75600, 'dimension': [240, 315]}, '-branch': [{'stack': ['x-21204d05efc14993bc9e7c9b7e8d250c', 'x-73b9415234e742a29fbe5be85c5d88b6'], 'child': 9999, 'path': 'https:/upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Misc_pollen.jpg/315px-Misc_pollen.jpg', 'show': [True, True, True]}], '-date': '2023-11-10T18:31:05.228696', '-tags': [], '-client': 'startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.saveDoc(doc)', '_attachments': {'v0.json': {'content_type': 'application/json', 'revpos': 3, 'digest': 'md5-0qOXUICaQXEtM+aYddor7Q==', 'length': 317, 'stub': True}}, '_id': 'p-a8d4c53345b548ea81ff79ca6dfdbe45'}
11-10 18:31:05|ERROR:Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 242, in saveDoc
    res = self.db.create_document(doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/database.py", line 191, in create_document
    doc.create()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/document.py", line 161, in create
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed missing_stub Invalid attachment stub in p-a8d4c53345b548ea81ff79ca6dfdbe45 for v0.json for url: http://127.0.0.1:5984/research

11-10 18:31:05|INFO: traceback remove:m-a4cfc9eea4d6457f80d9740fccbc2e13 startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.remove(doc['_id'])
11-10 18:31:05|ERROR:could not save, likely JSON issue; Check logging file
11-10 18:31:05|ERROR:could not save, likely JSON issue
11-10 18:31:05|ERROR:{'-name': 'simple.png', '-user': 'htsybenko', '-type': ['procedure'], 'metaVendor': {'Comment': 'Created with GIMP', 'fileExtension': 'png'}, 'metaUser': {'number all pixel': 480000}, '-branch': [{'stack': ['x-21204d05efc14993bc9e7c9b7e8d250c', 'x-73b9415234e742a29fbe5be85c5d88b6'], 'child': 9999, 'path': 'PastasExampleProject/002_DataFiles/simple.png', 'show': [True, True, True]}], '-date': '2023-11-10T18:31:05.238590', 'comment': '', '-tags': [], '-client': 'startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.saveDoc(doc)', '_attachments': {'v0.json': {'content_type': 'application/json', 'revpos': 3, 'digest': 'md5-av/W46hlYeaBRYE2QWLtHw==', 'length': 371, 'stub': True}}, '_id': 'p-ccd0e5023aed45a79cb20b654d5aee89'}
11-10 18:31:05|ERROR:Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 242, in saveDoc
    res = self.db.create_document(doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/database.py", line 191, in create_document
    doc.create()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/document.py", line 161, in create
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed missing_stub Invalid attachment stub in p-ccd0e5023aed45a79cb20b654d5aee89 for v0.json for url: http://127.0.0.1:5984/research

11-10 18:31:05|INFO: traceback remove:m-edefca99c94c4973ad66d7e85d85cc2b startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.remove(doc['_id'])
11-10 18:31:05|ERROR:could not save, likely JSON issue; Check logging file
11-10 18:31:05|ERROR:could not save, likely JSON issue
11-10 18:31:05|ERROR:{'-name': 'Example_SOP.md', 'comment': '', '-user': 'htsybenko', '-type': ['procedure'], 'metaVendor': {'fileExtension': 'md'}, 'metaUser': {}, '-branch': [{'stack': ['x-21204d05efc14993bc9e7c9b7e8d250c'], 'child': 9999, 'path': 'StandardOperatingProcedures/Example_SOP.md', 'show': [True, True]}], '-date': '2023-11-10T18:31:05.244808', '-tags': [], '-client': 'startMain()|app.exec()|self.triggered.connect(lambda : widget.execute(command))|self.comm.formDoc.emit(intersectionDict)|ret = formWindow.exec()|self.db.saveDoc(doc)', 'content': '# Put sample in instrument\n# Do something\nDo not forget to\n- not do anything wrong\n- **USE BOLD LETTERS**', '_attachments': {'v0.json': {'content_type': 'application/json', 'revpos': 3, 'digest': 'md5-+T954rr0i4/CV4WxjoBpRw==', 'length': 234, 'stub': True}}, '_id': 'p-64de321a23e04759b9a569442db5b55d'}
11-10 18:31:05|ERROR:Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 242, in saveDoc
    res = self.db.create_document(doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/database.py", line 191, in create_document
    doc.create()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/document.py", line 161, in create
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed missing_stub Invalid attachment stub in p-64de321a23e04759b9a569442db5b55d for v0.json for url: http://127.0.0.1:5984/research

11-10 18:31:05|DEBUG:details:changeDetails |redraw|
11-10 18:31:05|DEBUG:table:changeTable |||
11-10 18:31:05|DEBUG:table:changeTable |measurement||
11-10 18:31:06|DEBUG:table:changeTable |procedure|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:31:07|DEBUG:table:changeTable |sample|x-21204d05efc14993bc9e7c9b7e8d250c|
11-10 18:31:08|DEBUG:table:changeTable |measurement|x-21204d05efc14993bc9e7c9b7e8d250c|

**Comment by SteffenBrinckmann** [comment] 2023-11-14 11:12
@HTsybenko this is a bug; at least the first part, likely the second part too. End of may 2023, I tried to fix 
- "When unidentified files are assigned to measurement, "shasum not in measurement" and "shasum twice in view" messages appear"
And that fix was incomplete. 
A proper fix requires changes to the database, which I don't want to do inside a subversion (all 2.4 have the same database structure), but 2.5 will anyhow have a different database structure (project view permanence, ontology gone, ....) and hence I will put this fix into version 2.5 although it is a serious bug. 
Fix: shasum-> -shasum (exists for all docs that are files, non-empty); last line of useExtractor: if empty->recalc

BTW: the second step is even worse than you describe, as the documents are in-fact deleted (because it is not a measurement) and not created with the new type (procedure in your case); the error message in the log file points to it.
-> this is fixed in PR #139 

Please verify that the PR fixes the deletion issue: if it does change this issue to version 2.5 and remove the PR-exists label; please do not close the issue

**Comment by HTsybenko** [comment] 2023-11-17 14:49
The deletion issue seems to be fixed, and the items of measurements/procedures stay in the table they were moved to.

However, Measurements do not support "Content", and the Procedures cannot contain images. Therefore, during moving from one category to the other, this data gets lost. This can be a problem, for example, if the procedure item and its content were created via GUI and are not related to the specific file. In this case, it cannot be repaired using "Rerun extractors", if content was lost during moving.

**Comment by SteffenBrinckmann** [comment] 2023-12-14 11:39
seem to be fixed as it is a duplicate of " Data loss when changing Data Type #146 "

**Closed by SteffenBrinckmann** 2023-12-14 11:39 UTC
Labels: bug
